services:
  registration-server:
    build:
      context: .
      dockerfile: Dockerfile.registration-server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      credential-service:
        condition: service_started
      postgres:
        condition: service_healthy

  credential-service:
    build:
      context: .
      dockerfile: Dockerfile.credential-service
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: postgres:16
    restart: on-failure
    environment:
      - POSTGRES_DB=${DB_NAME:-gopasswordregis}
      # - POSTGRES_USER=${DB_USER:-gopasswordregis}
      - POSTGRES_PASSWORD=${DB_PASSWORD:-gopasswordregis_pass}
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 3s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
