# Build stage
FROM golang:1.26 AS build

WORKDIR /src

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/credential-service ./cmd/credential-service

# Run stage
FROM alpine:latest

COPY --from=build /out/credential-service /credential-service

EXPOSE 9090

ENTRYPOINT ["/credential-service"]