// Code generated by MockGen. DO NOT EDIT.
// Source: internal/genproto/credential/v1/credential_grpc.pb.go
//
// Generated by this command:
//
//	mockgen -source=internal/genproto/credential/v1/credential_grpc.pb.go -destination=internal/genproto/credential/v1/mocks/mocks_client.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	credentialv1 "github.com/minhloi0901/go-password-regis/internal/genproto/credential/v1"
	gomock "go.uber.org/mock/gomock"
	grpc "google.golang.org/grpc"
)

// MockCredentialServiceClient is a mock of CredentialServiceClient interface.
type MockCredentialServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialServiceClientMockRecorder
	isgomock struct{}
}

// MockCredentialServiceClientMockRecorder is the mock recorder for MockCredentialServiceClient.
type MockCredentialServiceClientMockRecorder struct {
	mock *MockCredentialServiceClient
}

// NewMockCredentialServiceClient creates a new mock instance.
func NewMockCredentialServiceClient(ctrl *gomock.Controller) *MockCredentialServiceClient {
	mock := &MockCredentialServiceClient{ctrl: ctrl}
	mock.recorder = &MockCredentialServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialServiceClient) EXPECT() *MockCredentialServiceClientMockRecorder {
	return m.recorder
}

// CreateCredential mocks base method.
func (m *MockCredentialServiceClient) CreateCredential(ctx context.Context, in *credentialv1.CreateCredentialRequest, opts ...grpc.CallOption) (*credentialv1.CreateCredentialResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CreateCredential", varargs...)
	ret0, _ := ret[0].(*credentialv1.CreateCredentialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredential indicates an expected call of CreateCredential.
func (mr *MockCredentialServiceClientMockRecorder) CreateCredential(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredential", reflect.TypeOf((*MockCredentialServiceClient)(nil).CreateCredential), varargs...)
}

// VerifyCredential mocks base method.
func (m *MockCredentialServiceClient) VerifyCredential(ctx context.Context, in *credentialv1.VerifyCredentialRequest, opts ...grpc.CallOption) (*credentialv1.VerifyCredentialResponse, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx, in}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "VerifyCredential", varargs...)
	ret0, _ := ret[0].(*credentialv1.VerifyCredentialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyCredential indicates an expected call of VerifyCredential.
func (mr *MockCredentialServiceClientMockRecorder) VerifyCredential(ctx, in any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, in}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCredential", reflect.TypeOf((*MockCredentialServiceClient)(nil).VerifyCredential), varargs...)
}

// MockCredentialServiceServer is a mock of CredentialServiceServer interface.
type MockCredentialServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockCredentialServiceServerMockRecorder
	isgomock struct{}
}

// MockCredentialServiceServerMockRecorder is the mock recorder for MockCredentialServiceServer.
type MockCredentialServiceServerMockRecorder struct {
	mock *MockCredentialServiceServer
}

// NewMockCredentialServiceServer creates a new mock instance.
func NewMockCredentialServiceServer(ctrl *gomock.Controller) *MockCredentialServiceServer {
	mock := &MockCredentialServiceServer{ctrl: ctrl}
	mock.recorder = &MockCredentialServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCredentialServiceServer) EXPECT() *MockCredentialServiceServerMockRecorder {
	return m.recorder
}

// CreateCredential mocks base method.
func (m *MockCredentialServiceServer) CreateCredential(arg0 context.Context, arg1 *credentialv1.CreateCredentialRequest) (*credentialv1.CreateCredentialResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCredential", arg0, arg1)
	ret0, _ := ret[0].(*credentialv1.CreateCredentialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCredential indicates an expected call of CreateCredential.
func (mr *MockCredentialServiceServerMockRecorder) CreateCredential(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCredential", reflect.TypeOf((*MockCredentialServiceServer)(nil).CreateCredential), arg0, arg1)
}

// VerifyCredential mocks base method.
func (m *MockCredentialServiceServer) VerifyCredential(arg0 context.Context, arg1 *credentialv1.VerifyCredentialRequest) (*credentialv1.VerifyCredentialResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyCredential", arg0, arg1)
	ret0, _ := ret[0].(*credentialv1.VerifyCredentialResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// VerifyCredential indicates an expected call of VerifyCredential.
func (mr *MockCredentialServiceServerMockRecorder) VerifyCredential(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyCredential", reflect.TypeOf((*MockCredentialServiceServer)(nil).VerifyCredential), arg0, arg1)
}

// mustEmbedUnimplementedCredentialServiceServer mocks base method.
func (m *MockCredentialServiceServer) mustEmbedUnimplementedCredentialServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCredentialServiceServer")
}

// mustEmbedUnimplementedCredentialServiceServer indicates an expected call of mustEmbedUnimplementedCredentialServiceServer.
func (mr *MockCredentialServiceServerMockRecorder) mustEmbedUnimplementedCredentialServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCredentialServiceServer", reflect.TypeOf((*MockCredentialServiceServer)(nil).mustEmbedUnimplementedCredentialServiceServer))
}

// MockUnsafeCredentialServiceServer is a mock of UnsafeCredentialServiceServer interface.
type MockUnsafeCredentialServiceServer struct {
	ctrl     *gomock.Controller
	recorder *MockUnsafeCredentialServiceServerMockRecorder
	isgomock struct{}
}

// MockUnsafeCredentialServiceServerMockRecorder is the mock recorder for MockUnsafeCredentialServiceServer.
type MockUnsafeCredentialServiceServerMockRecorder struct {
	mock *MockUnsafeCredentialServiceServer
}

// NewMockUnsafeCredentialServiceServer creates a new mock instance.
func NewMockUnsafeCredentialServiceServer(ctrl *gomock.Controller) *MockUnsafeCredentialServiceServer {
	mock := &MockUnsafeCredentialServiceServer{ctrl: ctrl}
	mock.recorder = &MockUnsafeCredentialServiceServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUnsafeCredentialServiceServer) EXPECT() *MockUnsafeCredentialServiceServerMockRecorder {
	return m.recorder
}

// mustEmbedUnimplementedCredentialServiceServer mocks base method.
func (m *MockUnsafeCredentialServiceServer) mustEmbedUnimplementedCredentialServiceServer() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "mustEmbedUnimplementedCredentialServiceServer")
}

// mustEmbedUnimplementedCredentialServiceServer indicates an expected call of mustEmbedUnimplementedCredentialServiceServer.
func (mr *MockUnsafeCredentialServiceServerMockRecorder) mustEmbedUnimplementedCredentialServiceServer() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "mustEmbedUnimplementedCredentialServiceServer", reflect.TypeOf((*MockUnsafeCredentialServiceServer)(nil).mustEmbedUnimplementedCredentialServiceServer))
}
