// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/credential/v1/credential.proto

package credentialv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProspectId    string                 `protobuf:"bytes,1,opt,name=prospect_id,json=prospectId,proto3" json:"prospect_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"` // plaintext
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCredentialRequest) Reset() {
	*x = CreateCredentialRequest{}
	mi := &file_proto_credential_v1_credential_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCredentialRequest) ProtoMessage() {}

func (x *CreateCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_credential_v1_credential_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCredentialRequest.ProtoReflect.Descriptor instead.
func (*CreateCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_credential_v1_credential_proto_rawDescGZIP(), []int{0}
}

func (x *CreateCredentialRequest) GetProspectId() string {
	if x != nil {
		return x.ProspectId
	}
	return ""
}

func (x *CreateCredentialRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreateCredentialRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CredentialId  string                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCredentialResponse) Reset() {
	*x = CreateCredentialResponse{}
	mi := &file_proto_credential_v1_credential_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCredentialResponse) ProtoMessage() {}

func (x *CreateCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_credential_v1_credential_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCredentialResponse.ProtoReflect.Descriptor instead.
func (*CreateCredentialResponse) Descriptor() ([]byte, []int) {
	return file_proto_credential_v1_credential_proto_rawDescGZIP(), []int{1}
}

func (x *CreateCredentialResponse) GetCredentialId() string {
	if x != nil {
		return x.CredentialId
	}
	return ""
}

type VerifyCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCredentialRequest) Reset() {
	*x = VerifyCredentialRequest{}
	mi := &file_proto_credential_v1_credential_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialRequest) ProtoMessage() {}

func (x *VerifyCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_credential_v1_credential_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialRequest.ProtoReflect.Descriptor instead.
func (*VerifyCredentialRequest) Descriptor() ([]byte, []int) {
	return file_proto_credential_v1_credential_proto_rawDescGZIP(), []int{2}
}

func (x *VerifyCredentialRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyCredentialRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type VerifyCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`                            // login success return true
	ProspectId    string                 `protobuf:"bytes,2,opt,name=prospect_id,json=prospectId,proto3" json:"prospect_id,omitempty"` // with valid = true
	Token         string                 `protobuf:"bytes,3,opt,name=token,proto3" json:"token,omitempty"`                             // with valid = true
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCredentialResponse) Reset() {
	*x = VerifyCredentialResponse{}
	mi := &file_proto_credential_v1_credential_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCredentialResponse) ProtoMessage() {}

func (x *VerifyCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_credential_v1_credential_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCredentialResponse.ProtoReflect.Descriptor instead.
func (*VerifyCredentialResponse) Descriptor() ([]byte, []int) {
	return file_proto_credential_v1_credential_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyCredentialResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyCredentialResponse) GetProspectId() string {
	if x != nil {
		return x.ProspectId
	}
	return ""
}

func (x *VerifyCredentialResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

var File_proto_credential_v1_credential_proto protoreflect.FileDescriptor

const file_proto_credential_v1_credential_proto_rawDesc = "" +
	"\n" +
	"$proto/credential/v1/credential.proto\x12\rcredential.v1\"r\n" +
	"\x17CreateCredentialRequest\x12\x1f\n" +
	"\vprospect_id\x18\x01 \x01(\tR\n" +
	"prospectId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\"?\n" +
	"\x18CreateCredentialResponse\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\tR\fcredentialId\"Q\n" +
	"\x17VerifyCredentialRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\"g\n" +
	"\x18VerifyCredentialResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1f\n" +
	"\vprospect_id\x18\x02 \x01(\tR\n" +
	"prospectId\x12\x14\n" +
	"\x05token\x18\x03 \x01(\tR\x05token2\xdd\x01\n" +
	"\x11CredentialService\x12c\n" +
	"\x10CreateCredential\x12&.credential.v1.CreateCredentialRequest\x1a'.credential.v1.CreateCredentialResponse\x12c\n" +
	"\x10VerifyCredential\x12&.credential.v1.VerifyCredentialRequest\x1a'.credential.v1.VerifyCredentialResponseBWZUgithub.com/minhloi0901/go-password-regis/internal/genproto/credential/v1;credentialv1b\x06proto3"

var (
	file_proto_credential_v1_credential_proto_rawDescOnce sync.Once
	file_proto_credential_v1_credential_proto_rawDescData []byte
)

func file_proto_credential_v1_credential_proto_rawDescGZIP() []byte {
	file_proto_credential_v1_credential_proto_rawDescOnce.Do(func() {
		file_proto_credential_v1_credential_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_credential_v1_credential_proto_rawDesc), len(file_proto_credential_v1_credential_proto_rawDesc)))
	})
	return file_proto_credential_v1_credential_proto_rawDescData
}

var file_proto_credential_v1_credential_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_credential_v1_credential_proto_goTypes = []any{
	(*CreateCredentialRequest)(nil),  // 0: credential.v1.CreateCredentialRequest
	(*CreateCredentialResponse)(nil), // 1: credential.v1.CreateCredentialResponse
	(*VerifyCredentialRequest)(nil),  // 2: credential.v1.VerifyCredentialRequest
	(*VerifyCredentialResponse)(nil), // 3: credential.v1.VerifyCredentialResponse
}
var file_proto_credential_v1_credential_proto_depIdxs = []int32{
	0, // 0: credential.v1.CredentialService.CreateCredential:input_type -> credential.v1.CreateCredentialRequest
	2, // 1: credential.v1.CredentialService.VerifyCredential:input_type -> credential.v1.VerifyCredentialRequest
	1, // 2: credential.v1.CredentialService.CreateCredential:output_type -> credential.v1.CreateCredentialResponse
	3, // 3: credential.v1.CredentialService.VerifyCredential:output_type -> credential.v1.VerifyCredentialResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_credential_v1_credential_proto_init() }
func file_proto_credential_v1_credential_proto_init() {
	if File_proto_credential_v1_credential_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_credential_v1_credential_proto_rawDesc), len(file_proto_credential_v1_credential_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_credential_v1_credential_proto_goTypes,
		DependencyIndexes: file_proto_credential_v1_credential_proto_depIdxs,
		MessageInfos:      file_proto_credential_v1_credential_proto_msgTypes,
	}.Build()
	File_proto_credential_v1_credential_proto = out.File
	file_proto_credential_v1_credential_proto_goTypes = nil
	file_proto_credential_v1_credential_proto_depIdxs = nil
}
