syntax = "proto3";

package credential.v1;

option go_package = "github.com/minhloi0901/go-password-regis/internal/genproto/credential/v1;credentialv1";

service CredentialService {
    rpc CreateCredential(CreateCredentialRequest) returns (CreateCredentialResponse);
    rpc VerifyCredential(VerifyCredentialRequest) returns (VerifyCredentialResponse);
}

message CreateCredentialRequest {
    string prospect_id = 1;
    string username = 2;
    string password = 3; // plaintext
}

message CreateCredentialResponse {
    string credential_id = 1;
}

message VerifyCredentialRequest {
    string username = 1;
    string password = 2;
}

message VerifyCredentialResponse {
    bool valid = 1; // login success return true
    string prospect_id = 2; // with valid = true
    string token = 3; // with valid = true
} 